### ISSUE TITLE
Package path building fails on Windows

### ISSUE THREAD

**Issue by ivanvanderbyl** [ivanvanderbyl/ember-cli-d3-primitive#9]
Related: https://github.com/spencer516/ember-d3-scale/issues/5#issuecomment-211417656

Essentially these lines https://github.com/ivanvanderbyl/ember-cli-d3-shape/blob/master/index.js#L14-L15 produce a slightly incorrect path on windows.

**Comment by XaserAcheron** [comment]
Did some debugging and that's indeed the trouble; looks like it's [already been fixed](https://github.com/ivanvanderbyl/ember-cli-d3-shape/commit/80c0525cab8dbc3ea75bab3b5b3e82c4ffe09797), though.

What's Happening in Xaser-land: `ember-d3-scale` is including an older version of `ember-cli-d3-shape` which doesn't use `path.sep`, hence the error on Windows. Updating that line fixed my issue, so that's the mystery (hopefully) solved.

**Comment by ivanvanderbyl** [comment]
@XaserAcheron thanks for confirming :)
